name: Build and publish
on: 
  workflow_dispatch:
    inputs:
      PackageVersion:
        description: "Package Version"
        required: true
  
jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'ApiFootball'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=${{ github.event.inputs.PackageVersion }}
      
#    - name: Publish
#      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
